const games = [
  {
    id: '1',
    name: 'random game',
    link: '/dealbreaker',
  },
  {
    id: '3',
    name: 'no wrong answers',
    link: '/nowronganswers',
    cards: [
      "Well it finally happened, you're the Piano Man. Which song are you singing us tonight?",
      "You just got accepted to Hogwarts! Why are you immediately expelled?",
      "If you could have a conversation with any fictional character, who would you choose and why?",
      "If you were stranded on a deserted island and could only bring three items with you, what would they be and why?",
      "If you could create a new holiday, what would it be called and how would it be celebrated?",
      "You have the power to travel back in time and witness any historical event. Which event would you choose to experience and why?",
      "If you were an ice cream flavor, what would you be called and what ingredients would you have?",
      "Imagine you discover a secret passageway in your house that leads to a hidden room. What do you find inside?",
      "If you could speak fluently in any language other than your native tongue, which language would you choose and why?",
      "Imagine you could be any mythical creature for a day. What creature would you choose to be and how would you spend your day?",
      "What famous villian (fictional or historic) would make the best prom date?",
      "If you could have a personal mascot that follows you around everywhere, what/who would it be and why?",
      "If you could replace one body part with a super-powered bionic version, which body part would you choose and what special abilities would it have?",
      "If you could invent a new flavor of potato chips that would make the headlines, what outrageous flavor combination would you create?",
      "If you could create a wacky holiday tradition, what would it be and how would people celebrate it?",
      "If you woke up one day with the ability to understand and speak the language of insects, what funny conversations do you imagine having with them?",
      "If you were a superhero with a completely useless superpower, what would your power be and how would you try to save the day?",
      "Which historical figure probably had the best butt?",
      "Time for a round of shots! But the bar only has condiments left. What condiment are you throwin' back?",
      "When it's all said and done, what's the sexiest ice cream flavor?",
      "Let's dance! Choose a historical figure to be your dance partner on a reality TV show, who would you pick and what dance style would you perform together?",
      "If you could have a personal theme song that played whenever you entered a room, what song would you choose and why?",
      "If you could turn any mundane task into an extreme sport, what task would you choose and what adrenaline-pumping elements would you add to it?",

    ]
  },
  {
    id: '4',
    name: 'cards against humanity',
    link: '/dealbreaker',
  },
  {
    id: '5',
    name: 'dealbreaker',
    link: '/dealbreaker',
    cards: [ 
{id: 1, text: 'Frantically searching for Bigfoot.'},
{id: 2, text: 'Drinking beer for breakfast.'},
{id: 3, text: 'Has a need to suck on your toes before bedtime.'},
{id: 4, text: 'Rhymes when the person speaks, even in serious conversations.'},
{id: 5, text: 'Wants to spend a little too much time with your sibling.'},
{id: 6, text: 'Insists on wearing a clown costume at every social event, including weddings and funerals.'},
{id: 7, text: 'Double-dips chips.'},
{id: 8, text: 'Does not take the last slice of pizza.'},
{id: 9, text: 'Does not allow you to borrow their hoodie.'},
{id: 10, text: 'One word, moocher.'},
{id: 11, text: 'Becomes paralyzed in any half of the body.'},
{id: 12, text: 'Comes out of the bathroom with flour on their mustache.'},
{id: 13, text: 'Self-diagnoses themselves.'},
{id: 14, text: 'Deep into the realm of conspiracy theories.'},
{id: 15, text: 'After a few months, it turns out the person is homeless.'},
{id: 16, text: 'Likes to snuggle up close when sleeping.'},
{id: 17, text: 'Does not like to snuggle when sleeping.'},
{id: 18, text: 'Always wails during sing-alongs.'},
{id: 19, text: 'Does not wash hands after using the toilet.'},
{id: 20, text: 'Refuses to eat anything that is not purple, even if it means surviving on grape juice and eggplants.'},
{id: 21, text: 'Believes that aliens have implanted a microchip in…nd that they are now part of a secret experiment.'},
{id: 22, text: 'Uses a hot air balloon as a mode of transportation.'},
{id: 23, text: 'Has a habit of picking their nose unfiltered.'},
{id: 24, text: "Has a habit of speaking in pirate slang and wants you to join in on the fun." },
{id: 25, text: "Refuses to use any form of technology and insists on living like it's the 19th century." } 
],
  },
  {
    id: '6',
    name: 'Bonding Questions',
    link: '/bonding',
    strangerCards: [
      'What quality do you value the most in a friend?',
      'If you could have one object with you in you pocket all the time, no matter the size. What would that object be?',
      'If you could change one thing about the world, what would it be and why?',
      'What is one goal or dream you have for your future?',
      'What is your favorite book or movie, and why does it resonate with you?',
      'What do you like cooking the most?',
      'Name a hobby or interest you would like to implement in your life?',
      'Do you believe in karma?',
      'Where would you like to go for a vacation?',
      'Have you ever broken a bone?',
      'Which food could you eat all year long?',
      'Are you a morning person or a night owl?',
      'Which art do you like the most?',
      "If you were stranded on a deserted island and could only bring three items with you, what would they be and why?"
    ],
    friendCards: [
      'What quality do you value the most in a friend?',
      'If your life were a TV show or movie, what genre would it be?',
      'What do you usually do to avoid an uncomfortable situation?',
      'Who is a brave person according to you?',
      'Tell one goal or dream you have in life?',
      'Which emotion drives you the most?',
      'What makes you feel most loved?',
      'What inspires you?',
      'Do you like solo trips or going out with everyone?',
      'Would you like to live on after your death as a ghost?',
      'What is the most expensive thing you own?',
      'What is your ideal weekend?',
      'If you could travel anywhere in the world, where would you go and what would you do there?',
      'Who was your biggest celebrity crush?',
      'When did you make yourself the proudest?',
      'Do you believe in ghosts?',
      'Buying what keeps you the happiest?',
      'What is your best skill?',
      'Which is the most used app on your phone?',
      'How would you choose to relax after a tiring day?',
      'What small things do people do that make your day?',
      'What would your first question be if you woke up after 10 years?',
      'Are you addicted to anything? What is it?',
    ],
    bestFriendCards: [
      'Describe a challenging experience you have had and how it shaped you as a person.',
      'What are you most afraid of?',
      'Do you listen to your heart or your head?',
      'How do you express your anger?',
      'What is the best phase of your life so far?',
      'If you are hurt, would you rather be left alone or be hugged tight?',
      'What is that one thing you would never exchange in your life for anything?',
      'Would you adopt a child left at your doorstep?',
      'Which date would you never forget?',
      'What is the one thing you always wanted as a child but did not get?',
      'What would you want to be remembered for?',
      'What makes you feel free?',
      'What makes you upset?',
    ],
    coupleCards: [
      'If you are hurt, would you rather be left alone or be hugged tight?',
      'How would you choose to relax after a tiring day?',
      'What is the one thing you always wanted as a child but did not get?',
      "What is your favorite memory of us as a couple, and why does it stand out to you?",
      "If we could travel anywhere in the world together, where would you want to go and why?",
      "What is one thing you appreciate about our relationship that you might not have expected when we first started dating?",
      "If you could choose one activity for us to do together regularly, what would it be and why?",
      "What is one personal goal you have for yourself, and how can I support you in achieving it?",
      "What is your love language, and how can we better express love and affection to each other in ways that resonate with our individual needs?",
      "What is something new or adventurous that you would like to try as a couple?",
      "What are three qualities or characteristics you admire in me, and how do they contribute to our relationship?",
      "How do you envision our future together, and what are some goals or dreams you have for us as a couple?",
      "What is one thing that you believe sets our relationship apart from others, and why is it significant to you?"
    ],
  },
  {
    id: '7',
    name: 'explosive kitten',
    link: '/dealbreaker',
  },
  {
    id: '8',
    name: 'icebreaker questions',
    link: '/dealbreaker',
  },
  {
    id: '9',
    name: 'create game with ai',
    link: '/',
  },
];

export default games;
