const games = [
  {
    id: '1',
    name: 'random game',
    link: '/dealbreaker',
  },
  {
    id: '2',
    name: 'never have i ever',
    link: '/dealbreaker',
  },
  {
    id: '3',
    name: 'no wrong answers',
    link: '/dealbreaker',
  },
  {
    id: '4',
    name: 'cards against humanity',
    link: '/dealbreaker',
  },
  {
    id: '5',
    name: 'dealbreaker',
    link: '/dealbreaker',
    cards: [
  'Söker frenetiskt efter Bigfoot.',
  'Dricker öl till frukost.',
  'Har ett behov av att suga på dina tår innan läggdags.',
  'Rimmar när personen pratar, även i seriösa konversationer',
  'Vill spendera lite för mycket tid med ditt syskon.',
  'Insisterar på att bära en clown kostym på varje socialt event, även bröllop och begravningar.',
  'Personen dubbeldippar chips',
  'Personen tar inte sista pizza slicen',
  'Tillåter inte att du lånar hens hoodie',
  'Ett ord, snytare',
  'Blir förlamad i valfri kroppshalva ',
  'Kommer ut från toaletten med mjöl på mustachen',
  'Självdiagnotiserar sig själv',
  'Är djupt inne i konspirationsteori träsket',
  'Efter några månader visar det sig att personen är personen är hemlös',
  'Gillar att ligga NÄRA och mysa när man sover',
  'Gillar inte att mysa när man sover',
  'Wailar alltid när det är allsång',
  'Tvättar inte händerna efter att en varit på toa', 
  "Vägrar att äta något som inte är lila, även om det betyder att överleva på druvjuice och eggplantor.",
  'Tror på att aliens har implanterat ett microchip i deras hjärnan och att dom nu är en del av ett hemligt experiment.',
  'Använder en luftballong som transportmedel',
  'Har en vana att ofiltrerat peta sig i näsan',
  '',
  ],
  },
  {
    id: '6',
    name: 'random game',
    link: '/dealbreaker',
  },
  {
    id: '7',
    name: 'would you rather',
    link: '/dealbreaker',
  },
  {
    id: '8',
    name: 'icebreaker questions',
    link: '/dealbreaker',
  },
  {
    id: '9',
    name: 'create game',
    link: '/dealbreaker',
  },
];

export default games;
