const games = [
  {
    id: '1',
    name: 'random game',
    link: '/dealbreaker',
  },
  {
    id: '2',
    name: 'never have i ever',
    link: '/dealbreaker',
  },
  {
    id: '3',
    name: 'no wrong answers',
    link: '/dealbreaker',
  },
  {
    id: '4',
    name: 'cards against humanity',
    link: '/dealbreaker',
  },
  {
    id: '5',
    name: 'dealbreaker',
    link: '/dealbreaker',
    cards: [
      'Frantically searching for Bigfoot.',
      'Drinking beer for breakfast.',
      'Has a need to suck on your toes before bedtime.',
      'Rhymes when the person speaks, even in serious conversations.',
      'Wants to spend a little too much time with your sibling.',
      'Insists on wearing a clown costume at every social event, including weddings and funerals.',
      'Double-dips chips.',
      'Does not take the last slice of pizza.',
      'Does not allow you to borrow their hoodie.',
      'One word, moocher.',
      'Becomes paralyzed in any half of the body.',
      'Comes out of the bathroom with flour on their mustache.',
      'Self-diagnoses themselves.',
      'Deep into the realm of conspiracy theories.',
      'After a few months, it turns out the person is homeless.',
      'Likes to snuggle up close when sleeping.',
      'Does not like to snuggle when sleeping.',
      'Always wails during sing-alongs.',
      'Does not wash hands after using the toilet.',
      'Refuses to eat anything that is not purple, even if it means surviving on grape juice and eggplants.',
      'Believes that aliens have implanted a microchip in their brain and that they are now part of a secret experiment.',
      'Uses a hot air balloon as a mode of transportation.',
      'Has a habit of picking their nose unfiltered.',
      'No more dealbreaker cards found!',
    ],
  },
  {
    id: '6',
    name: 'Bonding',
    link: '/bonding',
    cards: [
      'What quality do you value the most in a friend?',
      'If your life were a TV show or movie, what genre would it be?',
      'If you could have one object with you in you pocket all the time, no matter the size. What would that object be?',
      'What do you usually do to avoid an uncomfortable situation?',
      'Which emotion drives you the most?',
      'Who is a brave person according to you?',
      'What is one goal or dream you have for your future?',
      'What is your favorite book or movie, and why does it resonate with you?',
      'If you could travel anywhere in the world, where would you go and what would you do there?',
      'What makes you feel most loved?',
      'What are you most afraid of?',
      'Do you listen to your heart or your head?',
      'What inspires you?',
      'If you could change one thing about the world, what would it be and why?',
      'Describe a challenging experience you have had and how it shaped you as a person.',
      'Name a hobby or interest you would like to implement in your life?',
      'How do you express your anger?',
      'Do you like solo trips or going out with everyone?',
      'Would you like to live on after your death as a ghost?',
      'What was the best phase of your life?',
      'What is the most expensive thing you own?',
      'If you are hurt, would you rather be left alone or be hugged tight?',
      'What is your ideal weekend?',
      'Do you believe in karma?',
      'Where would you like to go for a vacation?',
      'Who was your biggest celebrity crush?',
      'When did you make yourself the proudest?',
      'What do you like cooking the most?',
      'What is that one thing you would never exchange in your life for anything?',
      'Do you believe in ghosts?',
      'Have you ever broken a bone?',
      'Which food could you eat all year long?',
      'Buying what keeps you the happiest?',
      'Would you adopt a child left at your doorstep?',
      'Are you a morning person or a night owl?',
      'What is your best skill?',
      'Which is the most used app on your phone?',
      'Which art do you like the most?',
      'Which date would you never forget?',
      'How would you choose to relax after a tiring day?',
      'What is the one thing you always wanted as a child but did not get?',
      'What small things do people do that make your day?',
      'What would your first question be if you woke up after 10 years?',
      'Are you addicted to anything? What is it?',
      'What would you want to be remembered for?',
      'What makes you feel free?',
      'What makes you upset?'
    ],
  },
  {
    id: '7',
    name: 'would you rather',
    link: '/dealbreaker',
  },
  {
    id: '8',
    name: 'icebreaker questions',
    link: '/dealbreaker',
  },
  {
    id: '9',
    name: 'create game',
    link: '/dealbreaker',
  },
];

export default games;
