import Head from 'next/head'
import { K2D } from 'next/font/google'
import Link from 'next/link';
import styles from '@/styles/Home.module.css'
import games from '../gamesData.js'

const k2d = K2D({ subsets: ['latin'], weight: '500' })

export default function Home() {
  return (
    <>
      <Head>
        <title>Pre-party</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${k2d.className}`}>
        <ul className={styles.gamesList}>
          {games.map(game => (
            <Link href={game.link}>
              <li key={game.id} className={styles.games}>{game.name}</li>
            </Link>
          ))}
        </ul>
      </main>
    </>
  );
}
